# version: "3.9"
services:
  cuda_compre:
    build: .
    container_name: final_compre
    restart: always
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - FACE_DETECTION_PLUGIN=insightface.FaceDetector@retinaface_r50_v1
      - CALCULATION_PLUGIN=insightface.Calculator@arcface_r100_v1
      - GPU_IDX=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"
